module.exports = {
  USER_RECEIVED: "USER_RECEIVED",

  TUTOR_RECEIVED: "TUTOR_RECEIVED",
  TUTOR_REGISTERED: "TUTOR_REGISTERED",
  TUTOR_DELETED: "TUTOR_DELETED",

  CLIENT_JOBS_RECEIVED: "CLIENT_JOBS_RECEIVED",
  TUTOR_JOBS_RECEIVED: "TUTOR_JOBS_RECEIVED",
  AVAILABLE_JOBS_RECEIVED: "AVAILABLE_JOBS_RECEIVED",
  JOB_CREATED: "JOB_CREATED",
  JOB_RECEIVED: "JOB_RECEIVED",
  JOB_DELETED: "JOB_DELETED",
  JOB_ACCEPTED: "JOB_ACCEPTED",

  TESTS_RECEIVED: "TESTS_RECEIVED",

  REGIONS_RECEIVED: "REGIONS_RECEIVED",

  QUALS_RECEIVED: "QUALS_RECEIVED",
  QUAL_REGISTERED: "QUAL_REGISTERED",
  QUAL_UNREGISTERED: "QUAL_UNREGISTERED"
};
